// Copyright 2026 Joseph King
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cli

import (
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var DryRun bool

var initSondePrompt = "This is a prompt generated by Sonde, A CLI tool, for your ingest."

var RootCmd = &cobra.Command{
	Use:   "sonde",
	Short: "Sonde: AI-powered terminal and container log analyzer",
	Long:  `Sonde is a CLI tool that uses AI to analyze terminal and container logs.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		// If nothing, help menu
		return cmd.Help()
	},
}

type CommandContext struct {
	Data   string
	Source string
	DryRun bool
}

func (ctx *CommandContext) setData(data string) {
	ctx.Data = data
}

func (ctx *CommandContext) setSource(source string) {
	ctx.Source = source
}

// truncateLogs helper to show just the tail end of what was grabbed
func truncateLogs(logs string, maxLines int) string {
	lines := strings.Split(logs, "\n")
	if len(lines) <= maxLines {
		return logs
	}
	return "... [truncated] ...\n" + strings.Join(lines[len(lines)-maxLines:], "\n")
}

func init() {
	RootCmd.PersistentFlags().BoolP("dry-run", "d", false, "Simulate the command without making changes")
}

func Execute() {
	if err := RootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}
