// Copyright 2026 Joseph King
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package integration

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
	"testing"
)

var expectedInitSondeOutput = "This is a prompt generated by Sonde, A CLI tool, for your ingest."
var expectedInitSummarizeOutput = "I have a user that requires a summary of the following action:\n"

func TestSummarizePipe(t *testing.T) {
	echoCmd := exec.Command("echo", "test-data")
	summarizeCmd := exec.Command("../build/sonde", "summarize", "--dry-run")

	echoCmd.Env = os.Environ()
	summarizeCmd.Env = os.Environ()

	stdout, err := echoCmd.StdoutPipe()
	if err != nil {
		t.Errorf("expected no error, got %v", err)
		return
	}

	defer stdout.Close() //nolint:errcheck

	if err := echoCmd.Start(); err != nil {
		t.Errorf("Failed to start echo command, got %v", err)
		return
	}

	summarizeCmd.Stdin = stdout
	output, err := summarizeCmd.Output()

	if err != nil {
		t.Errorf("expected no error, got %v", err)
	} else {
		var out = string(output)

		if out == "" {
			t.Errorf("Output is empty, got %s", out)
		}

		lastCmd, _ := getLastCommand(os.Getenv("SHELL"), 1)

		var expectedPipeLogs = fmt.Sprintf("command: %s\noutput: test-data", lastCmd) //added getting last actual command for now... Need to find a way to get this test running more proper... It does do what it is expected to do
		var expectedPrompt = fmt.Sprintf("[DRY-RUN]: %s %sSource: pipe\n%s", expectedInitSondeOutput, expectedInitSummarizeOutput, expectedPipeLogs)
		if expectedPrompt != strings.TrimSpace(out) {
			t.Errorf("Expected:\n%s\nGot:\n%s", expectedPrompt, out)
		}
	}
}

func TestEmptySummarizePipe(t *testing.T) {
	echoCmd := exec.Command("echo", "")
	summarizeCmd := exec.Command("../build/sonde", "summarize", "--dry-run")

	echoCmd.Env = os.Environ()
	summarizeCmd.Env = os.Environ()

	stdout, err := echoCmd.StdoutPipe()
	if err != nil {
		t.Errorf("expected no error, got %v", err)
		return
	}

	defer stdout.Close() //nolint:errcheck

	if err := echoCmd.Start(); err != nil {
		t.Errorf("Failed to start echo command, got %v", err)
		return
	}

	summarizeCmd.Stdin = stdout
	output, err := summarizeCmd.Output()

	if err == nil {
		t.Errorf("expected error, got %v", output)
	}
}

func TestSondeSummarizePipe(t *testing.T) {
	//TO DO
	// Once it actually captures the piped command incorporate this TestSondeSummarizePipe
	// Fo reference see expectedPrompt for TestSummarizePipe. It picks up the poiped command as the command to start the test suite
}

func TestSummarizeLast(t *testing.T) {

}
